kumuluzee:
  name: basketball-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://pg-events.clvqrwayazxs.eu-central-1.rds.amazonaws.com/users
      username: postgres
      password: postgres12
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDS
      http-health-check:
        connection-url: https://github.com/RSO-team/microservice-users
    metrics:
      web-instrumentation:
        - name: users-endpoint
          url-pattern: /v1/users/*
  rest-client:
    registrations:
      - class: users-api
        url: http://localhost:8084/v1
        read-timeout: 5000
  config:
#    consul:
#      agent: http://localhost:8500

rest-config:
  maintenance-mode: false
  api-token: htn12kss3
