kumuluzee:
  name: basketball-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://ella.db.elephantsql.com/dvvetzvi
      username: dvvetzvi
      password: fy5NwWDkRHNjf5ITtFlHmalPy38ckYRp
      max-pool-size: 3
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDS
      http-health-check:
        connection-url: https://github.com/RSO-team/microservice-users
    metrics:
      web-instrumentation:
        - name: users-endpoint
          url-pattern: /v1/users/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="906c451a-bc58-4cb6-8145-6a2d768e120b-ls.logit.io"
                                  port="26828" protocol="UDP">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="info" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: users-api
        url: http://localhost:8084/v1
        read-timeout: 5000
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://etcd:2379
  discovery:
    #cluster:
    etcd:
      hosts: http://etcd:2379
    ttl: 30
    ping-interval: 5
  cors-filter:
    servlet:
      allow-origin: "*"

rest-config:
  maintenance-mode: false
  api-token: htn12kss3
